version: '3'
services:
  configuration-wizard:
    image: "governikus/eidas-configuration-wizard:1.0.6"
    ports:
      - "8080:8080"
    volumes:
      - eidas-configuration:/opt/eidas-middleware/configuration
volumes:
  eidas-configuration:
    external: true
