version: '3'
services:
  configuration-wizard:
    image: "governikus/eidas-configuration-wizard:1.0.4-rc.1"
    ports: 
      - "443:8080"
    environment:
      SERVER_SSL_KEY_STORE: file:/opt/eidas-middleware/ssl.jks
      SERVER_SSL_KEY_STORE_TYPE: JKS
      SERVER_SSL_KEY_STORE_PASSWORD: 123456
      SERVER_SSL_KEY_PASSWORD: 123456
      SERVER_SSL_KEY_ALIAS: localhost
    volumes:
      - eidas-configuration:/opt/eidas-middleware/configuration
      - /path/on/host/to/keystore.jks:/opt/eidas-middleware/ssl.jks
volumes:
  eidas-configuration:
    external: true
