eidas_middleware:
  hostname:
    eumw: eumw-testbed-head.k8s.govkg.de
    admin_interface: eumw-testbed-head-admin.k8s.govkg.de
  port:
    server: 8443
    admin_interface: 8449
  image: dev-docker.governikus.de/governikus/eidas-middleware-application
  tag: latest
  hashed_password: $2a$10$EIwUSRpSu/eQzbtOw2dhvOJ2N6PIbTCGMhp9kc1sxEI2AAhKi0LxK
  volume: eidas-middleware-db
  database:
    name: eidas-middleware-db
    type: hsqldb
    path: /opt/eidas-middleware/database/
    pw: fallturm
    user: h2
  dvca14: true
